services:
  # Web service
  - type: web
    name: instagram-automation
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT
    healthCheckPath: /health
    plan: free
    autoDeploy: true
    envVars:
      - key: IG_USER_ID
        sync: false
      - key: IG_ACCESS_TOKEN
        sync: false
